Update devsecops.yml

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -17,6 +17,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.ref || github.ref }}
 
       - name: Set up Python 3.11
         uses: actions/setup-python@v4
@@ -44,8 +45,7 @@ jobs:
         uses: gitleaks/gitleaks-action@v2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          args: detect --redact --exit-code=2 --verbose
+        run: gitleaks detect --redact --exit-code=2 --verbose --staged=false
 
   docker-build:
     runs-on: ubuntu-latest
@@ -58,23 +58,23 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-    - name: Build Docker image locally
-      run: |
-        docker build -t flask-app:latest .
+      - name: Build Docker image locally
+        run: |
+          docker build -t flask-app:latest .
 
-    - name: Run smoke test
-          run: |
-            docker run -d --name flask-test -p 5000:5000 flask-app:latest
-            sleep 5
-            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
-            if [ "$STATUS" -ne 200 ]; then
-              echo "Flask app failed to start. Status code: $STATUS"
-              docker logs flask-test
-              docker stop flask-test
-              docker rm flask-test
-              exit 1
-            else
-              echo "Flask app is running."
-            fi
+      - name: Run smoke test
+        run: |
+          docker run -d --name flask-test -p 5000:5000 flask-app:latest
+          sleep 5
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
+          if [ "$STATUS" -ne 200 ]; then
+            echo "Flask app failed to start. Status code: $STATUS"
+            docker logs flask-test
             docker stop flask-test
             docker rm flask-test
+            exit 1
+          else
+            echo "Flask app is running."
+          fi
+          docker stop flask-test
+          docker rm flask-test
