Update devsecops.yml

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -9,7 +9,7 @@ on:
       - main
 
 jobs:
-  build:
+  security-checks:
     runs-on: ubuntu-latest
 
     steps:
@@ -46,3 +46,35 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           args: detect --redact --exit-code=2 --verbose
+
+  docker-build:
+    runs-on: ubuntu-latest
+    needs: security-checks
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+    - name: Build Docker image locally
+      run: |
+        docker build -t flask-app:latest .
+
+    - name: Run smoke test
+          run: |
+            docker run -d --name flask-test -p 5000:5000 flask-app:latest
+            sleep 5
+            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
+            if [ "$STATUS" -ne 200 ]; then
+              echo "Flask app failed to start. Status code: $STATUS"
+              docker logs flask-test
+              docker stop flask-test
+              docker rm flask-test
+              exit 1
+            else
+              echo "Flask app is running."
+            fi
+            docker stop flask-test
+            docker rm flask-test
